name: Backend CI

on:
  push:
    paths:
      - 'ThoughtNestBackend/**'
  pull_request:
    paths:
      - 'ThoughtNestBackend/**'

jobs:
  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ThoughtNestBackend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Debug file presence
        run: |
          ls -l src/test/resources
          cat src/test/resources/application-test.properties || echo "NOT FOUND"

      - name: Build and run tests with test profile
        run: mvn clean verify -Dspring.profiles.active=test -Dtest=!SecurityIntegrationTest

      - name: (Optional) Build Docker image
        if: success()
        run: |
          docker build -t thoughtnest-backend .
